steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/angelic-bee-477417-t8/skripsi-be/skripsi-be:$COMMIT_SHA',
        '.'
      ]

  # Step 2: Push ke Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/angelic-bee-477417-t8/skripsi-be/skripsi-be:$COMMIT_SHA'
      ]

  # Step 3: Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'skripsi-backend',
        '--image', 'asia-southeast2-docker.pkg.dev/angelic-bee-477417-t8/skripsi-be/skripsi-be:$COMMIT_SHA',
        '--region', 'asia-southeast2',
        '--platform', 'managed',
        '--port', '8080',
        '--allow-unauthenticated',
        '--add-cloudsql-instances', 'angelic-bee-477417-t8:asia-southeast2:skripsi-db',
        '--set-env-vars', 'NODE_ENV=production,JWT_SECRET=${_JWT_SECRET},JWT_EXPIRES_IN=7d,CLOUD_SQL_CONNECTION_NAME=angelic-bee-477417-t8:asia-southeast2:skripsi-db'
      ]

images:
  - 'asia-southeast2-docker.pkg.dev/angelic-bee-477417-t8/skripsi-be/skripsi-be:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY